__title__ = 'orthogonal-cli'
__description__ = 'orthogonal-cli - CLI for the DataCrunch Tournament by CrunchDAO'
__version__ = '0.3.0'
__author__ = 'Enzo CACERES, Matteo MANZI'
__author_email__ = 'enzo.caceres@crunchdao.com'
__url__ = 'https://github.com/crunchdao/orthogonal-cli'
