__title__ = 'orthogonal-cli'
__description__ = 'orthogonal-cli - CLI of the Orthogonal CrunchDAO Platform'
__version__ = '0.1.0'
__author__ = 'Enzo CACERES'
__author_email__ = 'enzo.caceres@crunchdao.com'
__url__ = 'https://github.com/crunchdao/orthogonal-cli'
